### ISSUE TITLE
pytest tests/test_multi_period_constraints.py not working

### ISSUE THREAD

**Issue by MaGering** [oemof/oemof-tabular#121]
Since the merge of https://github.com/oemof/oemof-tabular/pull/120 `test_multi_period_constraints.py` is not working, although the checks had passed.

**Comment by nailend** [comment]
https://github.com/oemof/oemof-tabular/actions/runs/5856447128/job/15876175024#step:6:264

**Comment by nailend** [comment]
This will be done after the `oemof.solph` v.5.1 release. We will then also fix the version.

**Comment by nailend** [comment]
This is addressed in #122 and fixed in #123

**Comment by nailend** [comment]
This is addressed in #122 and fixed in #123
