### ISSUE TITLE
tools/postprocessing.py content needed in oemoflex

### ISSUE THREAD

**Issue by MaGering** [oemof/oemof-tabular#143]
The content of `postprocessing.py` has been deleted with this commit: https://github.com/oemof/oemof-tabular/commit/e6bc50d657ae48265f788d0681611c15beb55d1e

It's something that is needed [here](https://github.com/rl-institut/oemoflex/blob/e37c303c474cff5e6b4617f9b2ca49e7ff0970e8/oemoflex/model/datapackage.py#L348-L349) in oemoflex. Can you bring it back or if possible move it to oemflex repo, @henhuy?

**Comment by henhuy** [comment]
Hey @MaGering,

I tried to implemented a more general postprocessing approach in `oemof.tabular`.
If you look into it, you can find similar functionality to get component sequences and busses (see https://github.com/oemof/oemof-tabular/blob/dev/src/oemof/tabular/postprocessing/core.py#L70-L71).
Maybe this can be used (with small modifications maybe) to fulfill your needs?
If you want, we can have a look together.
Other possibility would be, to implement your functions as `Calculations` as well and either add them to tabular or have them locally in oemoflex.

**Comment by henhuy** [comment]
Having a second look, I suggest moving both functions `component_results` and `bus_results` into oemof-B3.
They have no further dependencies and it's the simplest option IMO. 
Also regarding dependencies

**Comment by iuljan** [comment]
can this be closed @MaGering?

**Comment by MaGering** [comment]
> can this be closed @MaGering?

No, we have not yet checked whether the solution proposed by @henhuy is applicable in the oemoflex repo. I will inform you as soon as this is done.

**Comment by MaGering** [comment]
With the merge of this PR https://github.com/rl-institut/oemoflex/pull/99 this issue will be resolved.

**Comment by MaGering** [comment]
Done! :)
