### ISSUE TITLE
oemof.solph tag on dev not correct?

### ISSUE THREAD

**Issue by MaGering** [oemof/oemof-tabular#158]
Current oemof.solph version on dev to does not seem to be quite right. This may not have been noticed when installing via pip. However, Poetry installs a different solph version in oemof-B3.

I'm a bit confused myself. In the setup.py it says [here](https://github.com/oemof/oemof-solph/blob/v0.5.2.dev1/setup.py) `version="0.5.2dev1",`.  Is pip following this version or the tag name? In any case, Poetry is clearly following the tag name. I just tried this with the branch fix/solph-version-on-dev. And with this branch the correct version of solph is installed in oemof-B3.

@nailend @henhuy could you have a look?

**Comment by iuljan** [comment]
Pip is looking at pypi for the version number. See [here](https://pypi.org/project/oemof.solph/#history). 

Tags are only checked when you install from github with 
`pip install git+https://github.com/...@v0.5.2.dev`


Somehow I must have overseen the "."
