### ISSUE TITLE
Move fuchur scenario functionality to oemof tabular 

### ISSUE THREAD

**Issue by simnh** [oemof/oemof-tabular#16]
This code is to go to oemof tabular. 

https://github.com/znes/fuchur/blob/b457ba91be115b9ef365733fb41d94f9d1b3d592/src/fuchur/cli.py#L30-L61

https://github.com/znes/fuchur/blob/b457ba91be115b9ef365733fb41d94f9d1b3d592/src/fuchur/__init__.py#L7-L22

However, as we do not have any scenario toml files provided in oemof tabular for scenario definition we might either provide an empty one or/and allow to specify a folder which is then used as scenario folder.

**Comment by jnnr** [comment]
This seems outdated. If you want to take this up again, please re-open.
