### ISSUE TITLE
Postprocessing does not work for components which add pyomo variables

### ISSUE THREAD

**Issue by henhuy** [oemof/oemof-tabular#174]
When postprocessing MIMO component from [`oemof.industry`](https://github.com/sedos-project/oemof.industry), postprocessing throws an MultIndexError as key from oemof_data is not only holding input and output node, but instead holds group and current period for a sequence series (i.e. key equals: `("mimo", "group0", 0)`).
In order to fix this, I would simply neglect oemof keys holding more than 2 entries (fo in- and output).

**Comment by Bachibouzouk** [comment]
Hello, just to be sure I understand: how will the results be postprocessed then if you ignore them?

**Comment by henhuy** [comment]
> Hello, just to be sure I understand: how will the results be postprocessed then if you ignore them?

These are MIMO internal results, which are not meant to be visible for the user...
