### ISSUE TITLE
Error: Inferring metadata on Windows

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-tabular#27]
When inferring metadata on Windows, we (or @juliusmeier, to be precise) could not successfully load the energy system.

**How to replicate:**
Open a terminal and change the current directory to `src/oemof/tabular/examples/datapackages/dispatch`. Then, run `python scripts/infer.py`. This should reproduce the existing `data/datapackage.json`.

**Hypothesis:**
This arises due to the path separator in "path" entries in datapackage.json. Path separators of datapackage.json inferred on Windows look like this, e.g.:

"path": "data/elements\\electricity-transmission.csv"

**Observations:**

If we replace the \\ with /, the datapackage can be run without a problem.

**Questions**
Have other observed this, too? 

Can we fix this by adapting tabular.datapackage.building.infer_metadata() such that all paths are separated with "/"?

**Comment by jnnr** [comment]
@FelixMau: Can you reproduce this bug?

**Comment by jnnr** [comment]
@srhbrnds, could you check this on your machine?

**Comment by srhbrnds** [comment]
@jnnr I will try to reproduce this bug today.

**Comment by srhbrnds** [comment]
I tried to rerun the example on branch `fixes/metadata-windows` and receive the following error:
`FileNotFoundError: [Errno 2] No such file or directory: 'foreign_keys.json'` 

It traces back to the `config.py` line 12
```
with open(FOREIGN_KEYS_FILE, "r") as fk_file:
    FOREIGN_KEYS = json.load(fk_file)
```
Since the file `foreign_keys.json` exits in /src/oemof/tabular/config/ I assume the path is still the problem. I debugged the config.py and received the following: _[FOREIGN_KEYS_FILE: [MYPATH]/src/oemof/tabular/config/foreign_keys.json]_ . 

Do you have any idea on how to solve this @jnnr ?

**Comment by jnnr** [comment]
> Do you have any idea on why the porblem occurs when running the script but not in debugger mode @jnnr ?

Maybe you are on different environments when you debug and when you run the script? Just guessing.

**Comment by jnnr** [comment]
> @jnnr I will try to reproduce this bug today. Shall i test on branch fixes/metadata-windows or another?

Thanks! fixes/metadata-windows is quite old and might not include all necessary changes. Could make sense to start a fresh branch to fix the problem - however you like!

**Comment by srhbrnds** [comment]
The problem was caused by a relational path, I managed to resolve it partially. I will push my changes tomorrow.

**Comment by jnnr** [comment]
After a discussion, we found out: Actually, we do not want to have os-dependent metadata. The standard is unix-style separators (https://specs.frictionlessdata.io/data-resource/#data-location). Therefore, `infer_metadata` should give `/` as separator on any os. 
Next, we can check if datapackages created like this can be run on any os.
