### ISSUE TITLE
Release v0.0.3

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-tabular#58]
### Preparation
* [x] Test the examples and start an issue for non working examples.
* [x] Keep an eye on open issues that are set to your release but seem to be forgotten.
* [x] Make sure oemof.solph 0.4.5 is on pypi.

### Checks on the day of release
*  [x] Close "forgotten" issues with a recapitulatory comment or set them to a later release if they are still important.
*  [x] Run examples and tests check the CI results
*  [x] Check the Changelog (can you do this, @MaGering?)
*  [x] Check if the *latest* documentation looks right at [readthedocs](https://oemof-tabular.rtfd.io).
* [x] Update AUTHORS.rst
* [x] Support python 3.7 to 3.9
* [x] Changelog links are broken (missing backslash)
* [x] Change version in setup.py, docs/conf.py, commits-since badge, tabular/__init__.py, 
* [x] Add new version in src/oemof/tabular/config/config.py "supported_oemof_tabular_versions"
* [x] Setup zenodo hook

The rest of the release process is described in https://github.com/oemof/oemof/wiki/How-to-release

**Comment by jnnr** [comment]
Python versions in setup.py are 3.4, 3.5, 3.6, but tests use 3.7.

**Comment by jnnr** [comment]
Have to change version in setup.py, docs/conf.py, commits-since badge, tabular/__init__.py

**Comment by henhuy** [comment]
> Which python version shall we keep supporting? 3.7, 3.8, 3.9 like oemof.solph?

Yes!

**Comment by jnnr** [comment]
I cannot publish on pypi because of the github dependency on oemof.solph:

```
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/                                                                                                                                                                     
Invalid value for requires_dist. Error: Can't have direct dependency: 'oemof.solph @ git+https://git@github.com/oemof/oemof-solph@v0.4#egg=oemof.solph'  
```

**Comment by jnnr** [comment]
Finally finished with pypi and zenodo upload :)
